// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrZSRvu5aD02SI6LtT8Vi1MSrWTR0Hf4',
    appId: '1:600024381389:web:9777f818e7f0137ef1b684',
    messagingSenderId: '600024381389',
    projectId: 'sentinel-app-311e5',
    authDomain: 'sentinel-app-311e5.firebaseapp.com',
    storageBucket: 'sentinel-app-311e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYrLPkhoPhe8qHuEmqNE876RZctJ9aHD0',
    appId: '1:600024381389:android:92211527d4023efff1b684',
    messagingSenderId: '600024381389',
    projectId: 'sentinel-app-311e5',
    storageBucket: 'sentinel-app-311e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlj32IqjI6ip3gyWVGTb0P_E7g9mxpgw4',
    appId: '1:600024381389:ios:ad52c05ff5f91efff1b684',
    messagingSenderId: '600024381389',
    projectId: 'sentinel-app-311e5',
    storageBucket: 'sentinel-app-311e5.firebasestorage.app',
    iosBundleId: 'com.example.sentinelNewApp',
  );
}
